name: Android Build and Publish

on:
  push:
    branches:
      - main

env:
  moduleVersion: ${{ vars.MODULE_VERSION }}
  moduleBuild: ${{ github.run_number }}
  token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Build Version
        run: bash ./.scripts/setup_build_version.sh
      - name: Setup Local Properties
        run: bash ./.scripts/setup_local_properties.sh
      - name: Build Module AAR
        run: ./gradlew :googlewallet:assembleRelease --stacktrace
      - name: Publish to Git Packages
        run: ./gradlew :googlewallet:publish
      - name: Create Tag and Add to GitHub
        run: bash ./.scripts/setup_add_tag.sh
      - name: Generate CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ env.moduleVersion }}.${{ env.moduleBuild }}"
          excludeTypes: chore,docs
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: "v${{ env.moduleVersion }}.${{ env.moduleBuild }}"
          tag: "v${{ env.moduleVersion }}.${{ env.moduleBuild }}"
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
